### ISSUE TITLE
l10n issues

### ISSUE THREAD

**Issue by asaage** [nextcloud/files_retention#173]
The translation looks a bit wonky.
I can see a mixture of german and english in the flow-definition panel but the notifications and e-mails are completely english.
I checked [files_retention/l10n/ de and de_DE files](https://github.com/nextcloud/files_retention/l10n/) which would in theory cover all the translations as far as i can see.
Any Idea what i can do? 
 
**System**
```
php 8.0
nextcloud 23.0.4
files_retention: 1.12.0
```
**Nextcloud configuration:**
```
        "default_language": "de",
        "default_locale": "de_DE",
```
**personal settings (user-profile)**
```
language: de_DE
```
**Browser:**
```
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
```

**Comment by tuxmaster5000** [comment]
I have the same problem on NC 23.0.5 and files_retention: 1.12.0.
Here an picture of the dialogue.
![bild](https://user-images.githubusercontent.com/837503/173232034-013f400d-ae96-45d9-9007-818339f9ec65.png)

**Comment by nickvergessen** [comment]
Yeah it's fixed in 24+ with https://github.com/nextcloud/files_retention/pull/159

**Comment by nickvergessen** [comment]
Triggered the backport for 23 and 22

**Comment by asaage** [comment]
Could you reopen this or should i create a new issue?
The fix applys only for the flow-definition panel.
But the notifications and e-mails are still not translated.

**Comment by nickvergessen** [comment]
Can you post a screenshot what you are talking about?
But yeah should be a new issue
